"""create initial database schema

Revision ID: c9703b1081fd
Revises: 
Create Date: 2026-09-19 10:37:05.686094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'c9703b1081fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='darukaa'
    )
    op.create_index(op.f('ix_darukaa_users_email'), 'users', ['email'], unique=True, schema='darukaa')
    op.create_index(op.f('ix_darukaa_users_id'), 'users', ['id'], unique=False, schema='darukaa')
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['darukaa.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='darukaa'
    )
    op.create_index(op.f('ix_darukaa_projects_id'), 'projects', ['id'], unique=False, schema='darukaa')
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['darukaa.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='darukaa'
    )
    op.create_index(op.f('ix_darukaa_sites_id'), 'sites', ['id'], unique=False, schema='darukaa')
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['darukaa.sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='darukaa'
    )
    op.create_index(op.f('ix_darukaa_analytics_id'), 'analytics', ['id'], unique=False, schema='darukaa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_darukaa_analytics_id'), table_name='analytics', schema='darukaa')
    op.drop_table('analytics', schema='darukaa')
    op.drop_index(op.f('ix_darukaa_sites_id'), table_name='sites', schema='darukaa')
    op.drop_table('sites', schema='darukaa')
    op.drop_index(op.f('ix_darukaa_projects_id'), table_name='projects', schema='darukaa')
    op.drop_table('projects', schema='darukaa')
    op.drop_index(op.f('ix_darukaa_users_id'), table_name='users', schema='darukaa')
    op.drop_index(op.f('ix_darukaa_users_email'), table_name='users', schema='darukaa')
    op.drop_table('users', schema='darukaa')
    # ### end Alembic commands ###
